import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { TableSchema, ColumnDefinition } from '../../schema/types';
import { loadCLIConfig } from '../lib/adminAdapter';
import { loadSchemasWithPaths } from '../lib/schemaLoader';

export interface ErDiagramOptions {
  output?: string;
  yes?: boolean;
}

export const DEFAULT_ER_DIAGRAM_FILENAME = 'ER-DIAGRAM.md';

function keyMarker(colName: string, col: ColumnDefinition, pkColumn: string): string {
  if (colName === pkColumn) return 'PK';
  if (col.ref) return 'FK';
  if (col.unique) return 'UK';
  return '';
}

/**
 * Renders `erDiagram` body only (no ```mermaid fences) so it can be embedded in a
 * Markdown file or tested directly against its text output.
 */
export function generateMermaidERDiagram(schemas: TableSchema[]): string {
  const knownTables = new Set(schemas.map((s) => s.name));
  const lines: string[] = ['erDiagram'];

  for (const schema of schemas) {
    const pkColumn = schema.pkColumn ?? '_id';
    lines.push(`    ${schema.name} {`);
    for (const [colName, col] of Object.entries(schema.columns)) {
      const marker = keyMarker(colName, col, pkColumn);
      const parts = [col.type, colName];
      if (marker) parts.push(marker);
      lines.push(`        ${parts.join(' ')}`);
    }
    lines.push('    }');
  }

  const relationLines: string[] = [];
  for (const schema of schemas) {
    for (const [colName, col] of Object.entries(schema.columns)) {
      if (!col.ref) continue;
      const [refTable] = col.ref.split('.');
      if (!knownTables.has(refTable)) continue; // dangling ref() — not registered on this adapter
      const cardinality = col.unique ? '||--||' : '||--o{';
      relationLines.push(`    ${refTable} ${cardinality} ${schema.name} : "${colName}"`);
    }
  }

  if (relationLines.length > 0) {
    lines.push('');
    lines.push(...relationLines);
  }

  return lines.join('\n');
}

function buildMarkdown(schemas: TableSchema[]): string {
  const diagram = generateMermaidERDiagram(schemas);

  const byActor = new Map<string, string[]>();
  for (const schema of schemas) {
    const list = byActor.get(schema.actor) ?? [];
    list.push(schema.name);
    byActor.set(schema.actor, list);
  }
  const tableList = [...byActor.entries()]
    .map(([actor, tables]) => `- **${actor}**: ${tables.sort().join(', ')}`)
    .join('\n');

  return [
    '# ER Diagram',
    '',
    `Auto-generated by \`lsdb erdiagram\` on ${new Date().toISOString()}. Re-run after schema changes to refresh.`,
    '',
    '## Tables by actor',
    '',
    tableList,
    '',
    '## Diagram',
    '',
    '```mermaid',
    diagram,
    '```',
    '',
  ].join('\n');
}

/** Suggests `name-1.ext`, bumping an existing trailing `-N` to `-(N+1)`. */
function nextCandidateName(filename: string): string {
  const ext = path.extname(filename);
  const base = path.basename(filename, ext);
  const match = base.match(/^(.*)-(\d+)$/);
  if (match) {
    return `${match[1]}-${parseInt(match[2], 10) + 1}${ext}`;
  }
  return `${base}-1${ext}`;
}

/**
 * Resolves the final write path, prompting the developer when the target already exists:
 * overwrite it, save under a different name (looped until a free/confirmed path is chosen),
 * or cancel. Returns null on cancel. `yes` bypasses the prompt and always overwrites.
 */
async function resolveOutputPath(initialPath: string, yes: boolean): Promise<string | null> {
  let candidate = initialPath;

  while (fs.existsSync(candidate)) {
    if (yes) return candidate;

    const { action } = await inquirer.prompt([
      {
        type: 'list',
        name: 'action',
        message: `${path.basename(candidate)} already exists. What would you like to do?`,
        choices: [
          { name: 'Overwrite existing file', value: 'overwrite' },
          { name: 'Save as a different file name', value: 'rename' },
          { name: 'Cancel', value: 'cancel' },
        ],
      },
    ]);

    if (action === 'overwrite') return candidate;
    if (action === 'cancel') return null;

    const { newName } = await inquirer.prompt([
      {
        type: 'input',
        name: 'newName',
        message: 'Enter a new file name:',
        default: nextCandidateName(path.basename(candidate)),
        validate: (input: string) => (input.trim().length > 0 ? true : 'File name cannot be empty'),
      },
    ]);

    candidate = path.join(path.dirname(candidate), newName.trim());
  }

  return candidate;
}

export async function erdiagramCommand(options: ErDiagramOptions = {}) {
  console.log(chalk.blue.bold('🗺️  Generating ER diagram...\n'));

  const config = loadCLIConfig();
  const loaded = loadSchemasWithPaths(config);

  if (loaded.length === 0) {
    console.log(chalk.yellow('⚠️  No schemas found'));
    return;
  }

  const schemas = loaded.map((l) => l.schema);
  const markdown = buildMarkdown(schemas);

  const requestedPath = options.output
    ? path.resolve(process.cwd(), options.output)
    : path.join(process.cwd(), DEFAULT_ER_DIAGRAM_FILENAME);

  const outPath = await resolveOutputPath(requestedPath, options.yes ?? false);
  if (!outPath) {
    console.log(chalk.gray('Cancelled.'));
    return;
  }

  fs.writeFileSync(outPath, markdown);
  console.log(chalk.green(`✅ ER diagram written to ${outPath}`));
  console.log(chalk.cyan(`\n${schemas.length} table(s) diagrammed`));
}

export default erdiagramCommand;
