import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { TableSchema } from '../../schema/types';
import { resolveActorName } from '../../utils/actorConfig';
import { resolveConfigPath, TOKENS_FILENAME } from '../../utils/cliFiles';

interface ExportDataOptions {
  output?: string;
  table?: string;
  allUsers?: boolean;
  dryRun?: boolean;
}

function loadSchemas(
  config: { actors: Array<{ name?: string; role?: string } | string>; schemasDir?: string }
): TableSchema[] {
  const schemas: TableSchema[] = [];
  const schemasRoot = config.schemasDir
    ? path.resolve(process.cwd(), config.schemasDir)
    : path.join(process.cwd(), 'schemas');

  for (const actorEntry of config.actors) {
    const actor = resolveActorName(actorEntry);
    const actorDir = path.join(schemasRoot, actor);
    if (!fs.existsSync(actorDir)) continue;

    const files = fs.readdirSync(actorDir).filter((f) => f.endsWith('.ts') || f.endsWith('.js'));
    for (const file of files) {
      try {
        const schema = require(path.join(actorDir, file)).default;
        if (schema?.columns) schemas.push(schema);
      } catch {
        // skip unloadable files
      }
    }
  }

  return schemas;
}

// Serialises a schema to a JSON literal safe for embedding in generated JS.
// RegExp patterns are intentionally dropped — not needed for read-only export.
function schemaToLiteral(schema: TableSchema): string {
  const safe = {
    name: schema.name,
    actor: schema.actor,
    timestamps: schema.timestamps,
    softDelete: schema.softDelete,
    pkColumn: schema.pkColumn,
    columns: Object.fromEntries(
      Object.entries(schema.columns).map(([k, v]) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { pattern: _pattern, ...rest } = v;
        return [k, rest];
      })
    ),
  };
  return JSON.stringify(safe);
}

export function generateExportDataScript(schemas: TableSchema[], allUsers = false): string {
  const adminSchemas = schemas.filter((s) => s.actor === 'admin');
  const userSchemas = schemas.filter((s) => s.actor !== 'admin');

  // Build a role → table-names map for the --all-users section
  const roleTablesMap: Record<string, string[]> = {};
  for (const s of userSchemas) {
    if (!roleTablesMap[s.actor]) roleTablesMap[s.actor] = [];
    roleTablesMap[s.actor].push(s.name);
  }

  const commandName = allUsers ? 'lsdb export-data --all-users' : 'lsdb export-data';
  const scriptDesc = allUsers
    ? 'Exports admin sheet data AND all registered user sheets'
    : 'Exports admin sheet data only';

  const lines: string[] = [
    '/**',
    ` * longcelot-sheet-db → Production DB Data Export Script`,
    ` * Generated by: ${commandName}`,
    ` * ${scriptDesc}`,
    ' *',
    ' * Steps:',
    ' *   1. Install your production DB adapter (e.g. @prisma/client)',
    ' *   2. Replace the stub insertRow() with your real DB write',
    ' *   3. Run: node export-data.js',
    ' */',
    '',
    "const { createSheetAdapter } = require('longcelot-sheet-db');",
    "require('dotenv').config();",
    '',
    '// Schemas embedded at generation time (pattern validators omitted — read-only export)',
    'const schemas = [',
    ...schemas.map((s) => `  ${schemaToLiteral(s)},`),
    '];',
    '',
    'async function exportData() {',
    '  const adapter = createSheetAdapter({',
    '    adminSheetId: process.env.ADMIN_SHEET_ID,',
    '    credentials: {',
    '      clientId: process.env.GOOGLE_CLIENT_ID,',
    '      clientSecret: process.env.GOOGLE_CLIENT_SECRET,',
    '      redirectUri: process.env.GOOGLE_REDIRECT_URI,',
    '    },',
    `    tokens: require('./${TOKENS_FILENAME}'),`,
    '  });',
    '',
    '  adapter.registerSchemas(schemas);',
    '',
    '  // ---------- Replace this stub with your real DB client ----------',
    '  async function insertRow(tableName, row, userId) {',
    "    console.log(`  INSERT INTO ${tableName}:`, JSON.stringify(row));",
    '    // e.g. await prisma[tableName].create({ data: row });',
    '    // userId is provided for user-sheet rows so you can associate them with the correct user FK',
    '  }',
    '  // ----------------------------------------------------------------',
    '',
  ];

  // Admin tables section
  if (adminSchemas.length > 0) {
    lines.push("  // ─── Admin tables ───────────────────────────────────────────────────────");
    lines.push("  const adminCtx = adapter.withContext({ userId: 'export-cli', actor: 'admin', actorSheetId: process.env.ADMIN_SHEET_ID });");
    lines.push('');

    for (const schema of adminSchemas) {
      lines.push(`  // ─── ${schema.name} ───`);
      lines.push(`  console.log('\\nExporting table: ${schema.name}...');`);
      lines.push(`  try {`);
      lines.push(`    const rows = await adminCtx.table('${schema.name}').findMany({});`);
      lines.push(`    console.log(\`  Found \${rows.length} row(s)\`);`);
      lines.push(`    for (const row of rows) { await insertRow('${schema.name}', row); }`);
      lines.push(`    console.log(\`  ✓ ${schema.name}: \${rows.length} rows exported\`);`);
      lines.push(`  } catch (err) {`);
      lines.push(`    console.error(\`  ✖ ${schema.name} failed:\`, err.message);`);
      lines.push(`  }`);
      lines.push('');
    }
  }

  // User sheets section (only when --all-users)
  if (allUsers && userSchemas.length > 0) {
    lines.push("  // ─── User sheets (--all-users) ──────────────────────────────────────────");
    lines.push(`  const ROLE_TABLES = ${JSON.stringify(roleTablesMap, null, 4).replace(/\n/g, '\n  ')};`);
    lines.push('');
    lines.push("  console.log('\\nFetching registered users for per-user export...');");
    lines.push('  try {');
    lines.push("    const adminCtxForUsers = adapter.withContext({ userId: 'export-cli', actor: 'admin', actorSheetId: process.env.ADMIN_SHEET_ID });");
    lines.push("    const users = await adminCtxForUsers.table('users').findMany({});");
    lines.push('    console.log(`  Found ${users.length} user(s)\\n`);');
    lines.push('');
    lines.push('    for (const user of users) {');
    lines.push('      if (!user.actor_sheet_id) continue;');
    lines.push('      const roleTables = ROLE_TABLES[user.role] || [];');
    lines.push('      if (!roleTables.length) continue;');
    lines.push('');
    lines.push('      console.log(`\\n── User: ${user.user_id} (${user.role}) → ${user.actor_sheet_id}`);');
    lines.push('      const userCtx = adapter.withContext({ userId: user.user_id, actor: user.role, actorSheetId: user.actor_sheet_id });');
    lines.push('');
    lines.push('      for (const tableName of roleTables) {');
    lines.push('        console.log(`  Exporting ${tableName}...`);');
    lines.push('        try {');
    lines.push('          const rows = await userCtx.table(tableName).findMany({});');
    lines.push('          console.log(`    Found ${rows.length} row(s)`);');
    lines.push('          for (const row of rows) { await insertRow(tableName, row, user.user_id); }');
    lines.push('          console.log(`    ✓ ${tableName}: ${rows.length} rows exported`);');
    lines.push('        } catch (err) {');
    lines.push('          console.error(`    ✖ ${tableName} failed:`, err.message);');
    lines.push('        }');
    lines.push('      }');
    lines.push('    }');
    lines.push('  } catch (err) {');
    lines.push("    console.error('\\n✖ Failed to fetch users for --all-users export:', err.message);");
    lines.push('  }');
    lines.push('');
  } else if (!allUsers && userSchemas.length > 0) {
    // Hint that --all-users exists
    lines.push("  // Tip: run `lsdb export-data --all-users` to also export all registered user sheets");
    lines.push('');
  }

  lines.push("  console.log('\\nData export complete.');");
  lines.push('}');
  lines.push('');
  lines.push('exportData().catch(console.error);');
  lines.push('');

  return lines.join('\n');
}

export async function exportDataCommand(options: ExportDataOptions) {
  console.log(chalk.blue.bold('📦 Generating data export script...\n'));

  require('dotenv').config();

  let config: { actors: Array<{ name?: string; role?: string } | string>; schemasDir?: string };
  try {
    config = require(resolveConfigPath()).default;
  } catch {
    console.error(chalk.red('❌ lsdb.config.ts not found. Run: lsdb init'));
    process.exit(1);
  }

  let schemas = loadSchemas(config);

  if (options.table) {
    schemas = schemas.filter((s) => s.name === options.table);
    if (schemas.length === 0) {
      console.error(chalk.red(`❌ No schema found for table: ${options.table}`));
      process.exit(1);
    }
  }

  if (schemas.length === 0) {
    console.log(chalk.yellow('⚠️  No schemas found. Nothing to export.'));
    return;
  }

  const adminSchemas = schemas.filter((s) => s.actor === 'admin');
  const userSchemas = schemas.filter((s) => s.actor !== 'admin');

  console.log(chalk.cyan(`Found ${schemas.length} table(s):`));
  for (const s of schemas) {
    console.log(`  ${chalk.white(s.name)} ${chalk.gray(`(${s.actor})`)}`);
  }
  console.log();

  if (options.dryRun) {
    console.log(chalk.yellow('[DRY RUN] Script would be written — no file created.\n'));
    console.log(chalk.bold('Export plan:'));
    console.log(`  Admin tables: ${adminSchemas.map((s) => s.name).join(', ') || '(none)'}`);

    if (options.allUsers && userSchemas.length > 0) {
      const roles = [...new Set(userSchemas.map((s) => s.actor))];
      for (const role of roles) {
        const tables = userSchemas.filter((s) => s.actor === role).map((s) => s.name);
        console.log(`  ${role} tables: ${tables.join(', ')}`);
      }
      console.log(chalk.gray('\n  Note: --all-users will loop over all rows in admin users table at runtime.'));
    } else {
      for (const s of userSchemas) {
        console.log(`  ${s.actor}.${s.name}: ${Object.keys(s.columns).length} column(s) — not included (omit --all-users to skip user sheets)`);
      }
    }
    return;
  }

  const allUsers = options.allUsers ?? false;
  const script = generateExportDataScript(schemas, allUsers);
  const outDir = options.output ?? process.cwd();

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const outPath = path.join(outDir, 'export-data.js');
  fs.writeFileSync(outPath, script, 'utf-8');

  console.log(chalk.green(`✅ Data export script written to ${outPath}`));
  console.log();
  console.log(chalk.cyan('Next steps:'));
  console.log('  1. ' + chalk.white('Review the generated export-data.js'));
  console.log('  2. ' + chalk.white('Replace the insertRow() stub with your real DB client'));
  console.log('  3. ' + chalk.white('Run: node export-data.js'));
  if (!allUsers && userSchemas.length > 0) {
    console.log();
    console.log(chalk.gray(`Tip: Run with --all-users to also export all registered user sheets.`));
  }
  console.log();
  console.log(chalk.gray('Tip: Run `lsdb export --prisma` first to generate your Prisma schema.'));

  const missingEnv: string[] = [];
  for (const envVar of ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'ADMIN_SHEET_ID']) {
    if (!process.env[envVar]) missingEnv.push(envVar);
  }
  if (missingEnv.length > 0) {
    console.log();
    console.log(chalk.yellow(`⚠️  Missing env vars for script execution: ${missingEnv.join(', ')}`));
  }
}

export default exportDataCommand;
