import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { TableSchema } from '../../schema/types';

interface MigrateOptions {
  output?: string;
  table?: string;
  dryRun?: boolean;
}

function loadSchemas(config: { actors: Array<{ role: string } | string> }): TableSchema[] {
  const schemas: TableSchema[] = [];
  const schemasDir = path.join(process.cwd(), 'schemas');

  for (const actorEntry of config.actors) {
    const actor = typeof actorEntry === 'string' ? actorEntry : actorEntry.role;
    const actorDir = path.join(schemasDir, actor);
    if (!fs.existsSync(actorDir)) continue;

    const files = fs.readdirSync(actorDir).filter((f) => f.endsWith('.ts') || f.endsWith('.js'));
    for (const file of files) {
      try {
        const schema = require(path.join(actorDir, file)).default;
        if (schema?.columns) schemas.push(schema);
      } catch {
        // skip unloadable files
      }
    }
  }

  return schemas;
}

export function generateMigrationScript(schemas: TableSchema[]): string {
  const lines: string[] = [
    '/**',
    ' * longcelot-sheet-db → Production DB Migration Script',
    ' * Generated by: sheet-db migrate',
    ' *',
    ' * Steps:',
    ' *   1. Install your production DB adapter (e.g. @prisma/client)',
    ' *   2. Replace the stub insertRow() with your real DB write',
    ' *   3. Run: node migrate.js',
    ' */',
    '',
    "const { createSheetAdapter } = require('longcelot-sheet-db');",
    "require('dotenv').config();",
    '',
    'async function migrate() {',
    '  const adapter = createSheetAdapter({',
    '    adminSheetId: process.env.ADMIN_SHEET_ID,',
    '    credentials: {',
    '      clientId: process.env.GOOGLE_CLIENT_ID,',
    '      clientSecret: process.env.GOOGLE_CLIENT_SECRET,',
    '      redirectUri: process.env.GOOGLE_REDIRECT_URI,',
    '    },',
    '    tokens: require(\'.sheet-db-tokens.json\'),',
    '  });',
    '',
    '  // ---------- Replace this stub with your real DB client ----------',
    '  async function insertRow(tableName, row) {',
    '    console.log(`  INSERT INTO ${tableName}:`, row);',
    '    // e.g. await prisma[tableName].create({ data: row });',
    '  }',
    '  // ----------------------------------------------------------------',
    '',
  ];

  for (const schema of schemas) {
    lines.push(`  // ─── ${schema.name} (actor: ${schema.actor}) ───`);
    lines.push(`  console.log('\\nMigrating table: ${schema.name}...');`);
    lines.push(`  try {`);
    lines.push(`    const ctx = adapter.withContext({ userId: 'migrate-cli', role: '${schema.actor}', actorSheetId: process.env.ADMIN_SHEET_ID });`);
    lines.push(`    const rows = await ctx.table('${schema.name}').findMany({});`);
    lines.push(`    console.log(\`  Found \${rows.length} row(s)\`);`);
    lines.push(`    for (const row of rows) {`);
    lines.push(`      await insertRow('${schema.name}', row);`);
    lines.push(`    }`);
    lines.push(`    console.log(\`  ✓ ${schema.name}: \${rows.length} rows migrated\`);`);
    lines.push(`  } catch (err) {`);
    lines.push(`    console.error(\`  ✖ ${schema.name} failed:\`, err.message);`);
    lines.push(`  }`);
    lines.push('');
  }

  lines.push("  console.log('\\nMigration complete.');");
  lines.push('}');
  lines.push('');
  lines.push('migrate().catch(console.error);');
  lines.push('');

  return lines.join('\n');
}

export async function migrateCommand(options: MigrateOptions) {
  console.log(chalk.blue.bold('🚀 Generating migration script...\n'));

  require('dotenv').config();

  let config: { actors: Array<{ role: string } | string> };
  try {
    config = require(path.join(process.cwd(), 'sheet-db.config.ts')).default;
  } catch {
    console.error(chalk.red('❌ sheet-db.config.ts not found. Run: sheet-db init'));
    process.exit(1);
  }

  let schemas = loadSchemas(config);

  if (options.table) {
    schemas = schemas.filter((s) => s.name === options.table);
    if (schemas.length === 0) {
      console.error(chalk.red(`❌ No schema found for table: ${options.table}`));
      process.exit(1);
    }
  }

  if (schemas.length === 0) {
    console.log(chalk.yellow('⚠️  No schemas found. Nothing to migrate.'));
    return;
  }

  console.log(chalk.cyan(`Found ${schemas.length} table(s) to migrate:`));
  for (const s of schemas) {
    console.log(`  ${chalk.white(s.name)} ${chalk.gray(`(${s.actor})`)}`);
  }
  console.log();

  if (options.dryRun) {
    console.log(chalk.yellow('[DRY RUN] Script would be written — no file created.\n'));
    console.log(chalk.bold('Migration plan:'));
    for (const s of schemas) {
      const colCount = Object.keys(s.columns).length;
      console.log(`  ${s.name}: ${colCount} column(s), actor: ${s.actor}`);
    }
    return;
  }

  const script = generateMigrationScript(schemas);
  const outDir = options.output ?? process.cwd();

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const outPath = path.join(outDir, 'migrate.js');
  fs.writeFileSync(outPath, script, 'utf-8');

  console.log(chalk.green(`✅ Migration script written to ${outPath}`));
  console.log();
  console.log(chalk.cyan('Next steps:'));
  console.log('  1. ' + chalk.white('Review the generated migrate.js'));
  console.log('  2. ' + chalk.white('Replace the insertRow() stub with your real DB client'));
  console.log('  3. ' + chalk.white('Run: node migrate.js'));
  console.log();
  console.log(chalk.gray('Tip: Run `sheet-db export --prisma` first to generate your Prisma schema.'));

  // Verify env before giving run instructions
  const missingEnv: string[] = [];
  for (const envVar of ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'ADMIN_SHEET_ID']) {
    if (!process.env[envVar]) missingEnv.push(envVar);
  }
  if (missingEnv.length > 0) {
    console.log();
    console.log(chalk.yellow(`⚠️  Missing env vars for script execution: ${missingEnv.join(', ')}`));
  }
}

export default migrateCommand;
