/** Columns auto-generated by defineTable() — never define these manually, drop, or rename them. */
export const RESERVED_COLUMN_NAMES = ['_id', '_created_at', '_updated_at', '_deleted_at'] as const;
